baseURL = "https://hablab.whoi.edu/phyto-arm/"
languageCode = "en-us"
title = "PhytO-ARM"
pluralizelisttitles = false
ignorefiles = ["Archive/*", "Overview/*"]
theme = "hugo-geekdoc"
[markup]
  [markup.goldmark.renderer]
    unsafe = true