version: '3.6'

services:
    ros-master:
        image: ros:melodic-ros-core
        command: stdbuf -o L roscore
        restart: always

    ros-rosbag:
        image: ros:melodic-ros-core
        command: stdbuf -o L rosbag record --all --output-prefix=/rosbags/
        depends_on:
            - ros-master
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"
        volumes:
            - rosbags:/rosbags

    ros-nodes:
        build: .
        depends_on:
            - ros-master
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"
        ports:
            # Port we receive multicast NMEA strings on
            - "22335:22335/udp"

            # Port we serve a webserver on
            - "8092:8092/tcp"

    webviz:
        image: cruise/webviz
        
        # Note: On x86_64, we can use officially published Webviz images 
        build:
            context: ./webviz
            dockerfile: Dockerfile-static-webviz

        ports:
            - "8080:8080/tcp"

volumes:
    rosbags:
