#!/bin/sh
ROS_NODES_IMAGE="$(docker-compose images ros-nodes | tail -n 1 | tr -s ' ' | cut -d ' ' -f 4)"
exec docker run --rm -it \
    --network ros_default \
    --env "ROS_MASTER_URI=http://ros-master:11311" \
    "$ROS_NODES_IMAGE" \
    rosexec "$@"
