# InstrumentAction
# Runs instrument, winch position will hold until completed

# Goal

# General-purpose argument that an instrument can use to pass parameters to itself
string arg
# Result of movement that triggered this action, if any
phyto_arm/MoveToDepthResult move_result

---

# Result

string status
bool succeeded
std_msgs/Duration time_elapsed

---

# Feedback

std_msgs/Duration time_elapsed
