# MoveToDepth
# This action instructs the motor to lower to the current depth.

# Goal

float32 depth  # m

---

# Result

std_msgs/Duration time_elapsed

---

# Feedback

std_msgs/Duration time_elapsed

float32 depth  # m
float32 velocity  # m/s
