name: papi3_james_cook

launch_args:
    log_dir: /data/roslogs/
    rosbag_prefix: /data/rosbags/phyto-arm_jc283
    classifier: false
    ifcb_winch: false
    chanos_winch: false
    digital_logger: false
    network_data_capture: true

alerts:
    # You can post alert messages to Slack by creating an Incoming Webhook for your channel:
    - type: slack
      url: https://hooks.slack.com/services
# Node-specific configuration
network_data_capture: #optional.
    stats_interval: 60 #optional. Default is 60 seconds.
    print_stats: false #optional. Default is false. Useful for debugging connections
    topics:
        ship_ctd: # Name of the topic
            connection_type: "udp" # Can be "udp" or "tcp"
            port: 19015 # this is the port your systemD service is pointing to
            parsing_strategy: "delimited" # Can be "json_dict", "json_array", "raw", or "delimited"
            delimiter: ',\s*|\s+' #optional. Only used if parsing_strategy is "delimited"
            use_regex_delimiter: true
            # Field Descriptions: [0] Stream Identifier [$PRTSA], [1] Sentence Identifier [JCMES],
            # [2] Date [DD/MM/YY], [3] Time [hh:mm:ss.000], [4] Instrument ID [SBE45],
            # [5] NULL, [6] temp_h [temperature from SBE45], [7] cond [conductivity],
            # [8] salin [salinity], [9] sndspeed [sound velocity], [10] temp_r [temperature from SBE38]

            subtopics: #optional. If parsing_strategy is not raw, this will parse the data into subtopics
                ctdDate:
                    field_id: 2
                    type: "str"
                ctdTime:
                    field_id: 3
                    type: "str"
                ctdInstrumentID:
                    field_id: 4
                    type: "str"
                ctdTempSBE45_c:
                    field_id: 6
                    type: "float"
                ctdCond_sm:
                    field_id: 7
                    type: "float"
                ctdSal_psu:
                    field_id: 8
                    type: "float"
                ctdSound_mps:
                    field_id: 9
                    type: "float"
                ctdTempSBE38_c:
                    field_id: 10
                    type: "float"        
        ship_met: # Name of the topic
            connection_type: "udp" # Can be "udp" or "tcp"
            port: 19023 # this is the port your systemD service is pointing to
            parsing_strategy: "delimited" # Can be "json_dict", "json_array", "raw", or "delimited"
            delimiter: ',\s*|\s+' #optional. Only used if parsing_strategy is "delimited"
            use_regex_delimiter: true
        # Field Descriptions: [0] Stream Identifier [$PRTSA], [1] Sentence Identifier [JCMES],
        # [2] Date [DD/MM/YY], [3] Time [hh:mm:ss.000], [4] Instrument ID [surfm],
        # [5] NULL, [6] flow [Surface Water Instrument flow rate (l/min)],
        # [7] flou [Surface water fluorescence (V)], [8] trans [Surface water transmissivity (V)],
        # [9] speed [Surface wind relative speed (m/s)], [10] direct [Surface wind relative direction (°)],
        # [11] airtemp [Surface air temperature (°C)], [12] humid [Surface air humidity (%)],
        # [13] press [Surface air pressure (mbar)], [14] ppar [port side PAR sensor (volt x 10-5)],
        # [15] spar [starboard side PAR sensor (volt x 10-5)], [16] ptir [port side TIR sensor (volt x 10-5)],
        # [17] stir [starboard side TIR sensor (volt x 10-5)]

            subtopics: #optional. If parsing_strategy is not raw, this will parse the data into subtopics
                metDate:
                    field_id: 2   # Date [MM/DD/YY]
                    type: "str"
                metTime:
                    field_id: 3   # Time [hh:mm:ss.000]
                    type: "str"
                metFlowRate_lmin:
                    field_id: 6   # flow [Surface Water Instrument flow rate (l/min)]
                    type: "float"
                metFluorescence_v:
                    field_id: 7   # flou [Surface water fluorescence (V)]
                    type: "float"
                metTransmissivity_v:
                    field_id: 8   # trans [Surface water transmissivity (V)]
                    type: "float"
                metSurfaceWindSpeed_ms:
                    field_id: 9   # speed [Surface wind relative speed (m/s)]
                    type: "float"
                metSurfaceWindDirection_deg:
                    field_id: 10   # direct [Surface wind relative direction (°)]
                    type: "float"
                metSurfaceAirTemp_c:
                    field_id: 11  # airtemp [Surface air temperature (°C)]
                    type: "float"
                metSurfaceAirHumid_pct:
                    field_id: 12  # humid [Surface air humidity (%)]
                    type: "float"
                metSurfaceAirPressure_mbar:
                    field_id: 13  # press [Surface air pressure (mbar)]
                    type: "float"
                metPortPAR_v:
                    field_id: 14  # ppar [port side PAR sensor (volt x 10-5)]
                    type: "float"
                metStarPAR_v:
                    field_id: 15  # spar [starboard side PAR sensor (volt x 10-5)]
                    type: "float"
                metPortTIR_v:
                    field_id: 16  # ptir [port side TIR sensor (volt x 10-5)]
                    type: "float"
                metStarTIR_v:
                    field_id: 17  # stir [starboard side TIR sensor (volt x 10-5)]
                    type: "float"

gps:
    host: "172.17.0.1"
    check_fix_by_variance: false

lock_manager:
    # Use this to control how many motors can be in motion at once.
    max_moving_winches: 1


web:
    field_map:
       #optional
        commitHash: #optional
            # Will get value from COMMIT_HASH environment variable
            environment: COMMIT_HASH #optional
            # Default is optional for environment variables. Will error
            # if variable does not exist and no default provided
            default: c203cb925f2f9a2792f49589d15834c48a8008c7 #optional
        cruiseID:
            default: "RRS James Cook"
        ifcbLocation:
            default: "Deck Lab, main sink"
        ifcbWaterSource:
            default: "Flow through seawater intake, 6 m below water line (Bornemann Pumps SLH80-40 Hygienic Twin-Screw Pump). Tapped from Deck Lab sink."
        ctdDepth: #optional
            # Must have 'default' if not 'environment'
            default: 6.0 #optional
            # Optional 'topic' to update value
        gpsLatitude: #optional
            topic: /gps/fix #optional
            topic_field: latitude #optional
            default: -999.999 #optional
        gpsLongitude: #optional
            topic: /gps/fix #optional
            topic_field: longitude #optional
            default: -999.999 #optional
        gpsSource: #optional
            default: "RRS James Cook" #optional
        SBE45ModelSN: #optional
            default: "SBE 45, SN:0231"
        SBE45LastCal:  #optional
            default: "16 October, 2024" #optional
        SBE38ModelSN: #optional
            default: "SBE 38, SN:0490"
        SBE38LastCal:  #optional
            default: "03 January, 2024" #optional
        ctdTempSBE45_c: #optional
            topic: /ship_ctd/ctdTempSBE45_c #optional
            topic_field: data #optional
            default: -999.999 #optional
        ctdTempSBE38_c: #optional
            topic: /ship_ctd/ctdTempSBE38_c #optional
            topic_field: data #optional
            default: -999.999 #optional
        ctdSal_psu: #optional
            topic: /ship_ctd/ctdSal_psu #optional
            topic_field: data #optional
            default: -999.999 #optional
        ctdCond_sm: #optional
            topic: /ship_ctd/ctdCond_sm #optional
            topic_field: data #optional
            default: -999.999 #optional
        ctdSound_mps: #optional
            topic: /ship_ctd/ctdSound_mps #optional
            topic_field: data #optional
            default: -999.999 #optional
        metFlowRate_lmin: #optional
            topic: /ship_met/metFlowRate_lmin #optional
            topic_field: data #optional
            default: -999.999 #optional
        metFluorescence_v: #optional
            topic: /ship_met/metFluorescence_v #optional
            topic_field: data #optional
            default: -999.999 #optional
        metTransmissivity_v: #optional
            topic: /ship_met/metTransmissivity_v #optional
            topic_field: data #optional
            default: -999.999 #optional
        metSurfaceWindSpeed_ms: #optional
            topic: /ship_met/metSurfaceWindSpeed_ms #optional
            topic_field: data #optional
            default: -999.999 #optional
        metSurfaceWindDirection_deg: #optional
            topic: /ship_met/metSurfaceWindDirection_deg #optional
            topic_field: data #optional
            default: -999.999 #optional
        metSurfaceAirTemp_c: #optional
            topic: /ship_met/metSurfaceAirTemp_c #optional
            topic_field: data #optional
            default: -999.999 #optional
        metSurfaceAirHumid_pct: #optional
            topic: /ship_met/metSurfaceAirHumid_pct #optional
            topic_field: data #optional
            default: -999.999 #optional
        metSurfaceAirPressure_mbar: #optional
            topic: /ship_met/metSurfaceAirPressure_mbar #optional
            topic_field: data #optional
            default: -999.999 #optional
        metPortPAR_v: #optional
            topic: /ship_met/metPortPAR_v #optional
            topic_field: data #optional
            default: -999.999 #optional
        metStarPAR_v: #optional
            topic: /ship_met/metStarPAR_v #optional
            topic_field: data #optional
            default: -999.999 #optional
        metPortTIR_v: #optional
            topic: /ship_met/metPortTIR_v #optional
            topic_field: data #optional
            default: -999.999 #optional
        metStarTIR_v: #optional
            topic: /ship_met/metStarTIR_v #optional
            topic_field: data #optional
            default: -999.999 #optional
        #defaultOnly: #optional
        #    # No topic means this default value is permanent
        #    default: 'static_value' #optional

