seatrac:
  comms:
    connection:
      type: "UDP"
      udp_rx: 62001
      udp_tx: 62001
      udp_address: "10.1.20.88"

  outlets:
    - name: "starlink"
      outlet: 15

seatrac_starlink_manager:
  scheduled_on: "12:30"  # HH:MM, UTC timezone
  shutdown_reminder:     1200  # seconds
  soc_threshold:
    high: 95  # percent (minimum threshold for automatic activation)
    medium: 80  # percent (minimum threshold for daily activation)
