# ArmTask

# Only response needed

---

# Identifier for type of task
string name

# Depth at which task should be performed
float32 depth

# General purpose arguments to pass to payload when depth is reached
string[] args
