# ArmTask

# Only response needed

---

# If true no movement will be performed. Useful if there are no current tasks
bool hold

# Depth at which task should be performed
float32 depth

# General purpose argument to pass to instrument when depth is reached
string instrument_arg
